server:
 port: 8084

spring:
  application:
    name: RATING_SERVICE

  datasource:
    url: jdbc:postgresql://localhost:5432/microservices
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  config:
    import: optional:configserver:http://localhost:8086
#eureka:
#  client:
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#  instance:
#    prefer-ip-address: true
